language: cpp

matrix:
  include:
  - compiler: gcc
  - compiler: gcc
    env: CXXFLAGS="-std=c++11"
  - compiler: clang
  - compiler: clang
    env: CXXFLAGS="-std=c++11"

before_install: scripts/travis/before_install.sh
install: scripts/travis/install.sh
script: scripts/travis/script.sh

git:
  submodules: false

cache: apt
