language: cpp

matrix:
  include:
  - compiler: gcc
  - compiler: gcc
    env: CXXFLAGS="-std=c++11"
  - compiler: clang
  - compiler: clang
    env: CXXFLAGS="-std=c++11"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq --no-install-recommends doxygen graphviz
  - sudo apt-get install -qq libxml2-dev libxslt1-dev

script:
  - ./bootstrap && ./configure CXXFLAGS="-Werror $CXXFLAGS" && make && make check

git:
  submodules: false

cache: apt
