language: cpp

compiler:
  - gcc
  - clang

env:
  - CONFIGURE_OPTS="CXXFLAGS=-std=c++11"
  - CONFIGURE_OPTS=""

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq --no-install-recommends doxygen
  - sudo apt-get install -qq libxml2-dev libxslt1-dev

script:
  - ./bootstrap && ./configure $(CONFIGURE_OPTS) && make && make check

git:
  submodules: false

cache: apt
