language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq --no-install-recommends doxygen
  - sudo apt-get install -qq libxml2-dev libxslt1-dev libboost-dev libboost-iostreams-dev libboost-test-dev

script:
  - ./bootstrap && ./configure && make && make check

git:
  submodules: false

cache: apt
