language: cpp

compiler:
  - gcc
  - clang

env:
  - CXXFLAGS="-std=c++11"
  - CXXFLAGS=""

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq --no-install-recommends doxygen graphviz
  - sudo apt-get install -qq libxml2-dev libxslt1-dev

script:
  - ./bootstrap && ./configure CXXFLAGS="-Werror $CXXFLAGS" && make && make check

git:
  submodules: false

cache: apt
