language: cpp

matrix:
  include:
  - compiler: gcc
  - compiler: gcc
    env: TEST_DIST=1
  - compiler: gcc
    env: CXXFLAGS="-std=c++11"
  - addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env: SET_CXX="CC=gcc-8 CXX=g++-8"
  - compiler: clang
  - compiler: clang
    env: CXXFLAGS="-std=c++11"
  - env: HOST=i686-w64-mingw32
  - env: HOST=x86_64-w64-mingw32

before_install: scripts/travis/before_install.sh
install: scripts/travis/install.sh
script: scripts/travis/script.sh

git:
  submodules: false

cache: apt
